### ISSUE TITLE
db.putReturn should allow multiple pushdata elements

### ISSUE THREAD

**Issue by dfoderick** [the-bitcoin-token/bitcoin-token#2]
### Current behavior:
```
let out = await db.putReturn({"test":"0123456789"})
UnhandledPromiseRejectionWarning: Invalid Argument
```
### Expected behavior:
putReturn should save array and json data

### Details:
Currently the method signature is string but this is very limiting.
putReturn(data: string)
More data types should be supported.
putReturn(data: object)
putReturn(data: Array)

### Test Code
const testPutReturn = async() => {
    let testlen = 1
    let testnext = 1
    console.log(`testing ${testlen} ${testnext}`)
    let out = await db.putReturn({"test": "0123456789".repeat(testlen)})
    console.log(out)
}
testPutReturn()
### Stack Trace:
testing 1 1
(node:17348) UnhandledPromiseRejectionWarning: Invalid Argument
Error
    at new NodeError (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\errors\index.js:20:39)
    at Object.checkArgument (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\util\preconditions.js:13:13)
    at Function.Script.buildDataOut (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\script\script.js:795:5)
    at Q.addData (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\transaction.js:662:22)
    at Q.toReturnOutput (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\index.js:1:8720)
    at Q._to (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\index.js:1:8856)
    at Array.forEach (<anonymous>)
    at st.send (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\index.js:1:11388)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ClemensLey** [comment]
Agreed.
