### ISSUE TITLE
db.put allows someone to create a record (tx output) that cannot be updated (spent)

### ISSUE THREAD

**Issue by dfoderick** [the-bitcoin-token/bitcoin-token#3]
Steps to reproduce:
(1) db.put some large data (1000 bytes) => successful, because the data is hashed
(2) db.update with larger data ==> fails, because data has to be written unhashed in redeem script
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 1037

Stack Trace
```
(node:17524) UnhandledPromiseRejectionWarning: RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 947
    at writeU_Int8 (internal/buffer.js:559:11)
    at Buffer.writeUInt8 (internal/buffer.js:569:10)
    at BufferWriter.writeUInt8 (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\encoding\bufferwriter.js:37:7)
    at Function.sighashForForkId (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\sighash.js:103:12)
    at Function.sighash (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\sighash.js:157:22)
    at Function.sign (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\sighash.js:226:29)
    at publicKeysForPrivateKey.map.publicKey (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\input\multisigscripthash.js:64:24)
    at Array.map (<anonymous>)
    at MultiSigScriptHashInput.getSignatures (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\input\multisigscripthash.js:59:34)
    at inputs.forEach (C:\Users\Dave\Documents\GitHub\bittok\node_modules\bitcointoken\node_modules\bitcoinsource\src\transaction\transaction.js:944:31)
(node:17524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected behavior:
Probably, db.put should have some type of data limit protection? Perhaps user should be directed to use db.putReturn instead.

**Comment by ClemensLey** [comment]
Good point. One way to fix that would be to through an error in BitcoinSource when someone builds a p2sh script from a redeem script that is too big. Then BitcoinToken could catch the error to implement the data limit protection. Will leave this open while we work on fixing this in BitcoinSource

**Comment by ClemensLey** [comment]
We should try to figure out if this is a bug or a limit on the script size.

**Comment by dfoderick** [comment]
Excellent! That was a great bug to solve.
I can do more testing that will expose script limits but at least I will be getting past this bug.
